var oradb = require('./oradb.js');

function startToInstall(){
    const query = "create table fbe_psn_persons( " +
    "person_id number(15) generated by default on null as identity start with 1 increment by 1 , " +
    "nam_first_prson varchar2(50 char), nam_last_prson varchar2(100 char),dat_birth_prson date, " +
    "cod_nat_prson varchar2(15 char),cod_passport_prson varchar2(50 char),cod_econom_prson varchar2(50 char),cod_meli_prson varchar2(50 char)) " ;

    const result = oradb.runQuery(query);

    console.log("result:"+result);
    
}

startToInstall();
